In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import random 
from copy import deepcopy 




from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import matthews_corrcoef as MCC_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score

from catboost import Pool, cv
from catboost import CatBoostClassifier
from catboost import CatBoostRegressor

from collections import Counter 

from tqdm import tqdm

from IPython.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))

In [2]:
import phik

# Чтение данных

In [3]:
data = pd.read_csv('train.csv', low_memory=False)
data

,report_date,client_id,target,col1,col2,col3,col4,col5,col6,col7,...,col2654,col2655,col2656,col2657,col2658,col2659,col2660,col2661,col2662,col2663
0,2022-11-01,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.256261
1,2022-11-01,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7616803.0,7616803.0,7616803.0,NaN,NaN,NaN,7616803.0,7616803.0,7616803.0,0.256261
2,2022-05-01,6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.256261
3,2022-09-01,7,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.258682
4,2022-08-01,8,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.254164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14451,2022-07-01,1241,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.276902
14452,2022-09-01,1969,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.260516
14453,2022-02-01,7116,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.260005
14454,2021-08-01,7117,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.256261
14455,2022-03-01,849,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.293904

# Проверка данных на типы и их изменение

In [219]:
col_info = pd.DataFrame(data.nunique()).rename(columns = {0: 'n_values'})
uniq_values = []
types = []
count_values = []
target_phik = []

for column in tqdm(data.columns):
    
    x, y = data[['target', column]].T.values

    
    non_none_values = data[column].dropna()
    data_type = non_none_values.dtype
    uniq_values.append(data[column].unique())
    count_values.append(len(non_none_values))
    types.append(data_type)
    
    if data_type == 'object':
        data[column] = data[column].fillna(-404).apply(str)
    
    #target_phik.append(phik.phik_from_array(x, y, num_vars=['x']))

col_info['uniq_values'] = uniq_values
col_info['data_type'] = types
col_info['values_count'] = count_values
#col_info['target_phik'] = target_phik

100%|██████████████████████████████████████████████████████████████████████████████| 2666/2666 [01:05<00:00, 40.52it/s]

In [222]:
#col_info.sort_values('target_phik').to_excel('vdv.xlsx')

In [223]:
obj_cols = list(col_info[col_info['data_type'] == 'object'].index)
obj_cols

['report_date',
 'col49',
 'col50',
 'col51',
 'col52',
 'col53',
 'col54',
 'col55',
 'col56',
 'col57',
 'col58',
 'col59',
 'col60',
 'col61',
 'col62',
 'col63',
 'col64',
 'col85',
 'col86',
 'col87',
 'col88',
 'col89',
 'col90',
 'col91',
 'col92',
 'col93',
 'col94',
 'col95',
 'col96',
 'col97',
 'col98',
 'col99',
 'col100',
 'col129',
 'col130',
 'col131',
 'col132',
 'col133',
 'col134',
 'col135',
 'col136',
 'col137',
 'col138',
 'col139',
 'col140',
 'col141',
 'col142',
 'col143',
 'col144',
 'col145',
 'col146',
 'col147',
 'col148',
 'col149',
 'col150',
 'col151',
 'col152',
 'col153',
 'col154',
 'col155',
 'col156',
 'col157',
 'col158',
 'col159',
 'col160',
 'col161',
 'col162',
 'col163',
 'col164',
 'col165',
 'col166',
 'col167',
 'col168',
 'col169',
 'col170',
 'col171',
 'col172',
 'col173',
 'col174',
 'col175',
 'col176',
 'col181',
 'col182',
 'col183',
 'col184',
 'col185',
 'col186',
 'col187',
 'col188',
 'col189',
 'col190',
 'col191',
 'col192',
 'col193',
 'col194',
 'col195',
 'col196',
 'col201',
 'col202',
 'col203',
 'col204',
 'col205',
 'col206',
 'col207',
 'col208',
 'col209',
 'col210',
 'col211',
 'col212',
 'col213',
 'col214',
 'col215',
 'col216',
 'col221',
 'col222',
 'col223',
 'col224',
 'col225',
 'col226',
 'col227',
 'col228',
 'col237',
 'col238',
 'col239',
 'col240',
 'col241',
 'col242',
 'col243',
 'col244',
 'col457',
 'col458',
 'col459',
 'col460',
 'col461',
 'col462',
 'col463',
 'col464',
 'col465',
 'col466',
 'col467',
 'col468',
 'col469',
 'col470',
 'col471',
 'col472',
 'col513',
 'col514',
 'col515',
 'col516',
 'col517',
 'col518',
 'col519',
 'col520',
 'col521',
 'col522',
 'col523',
 'col524',
 'col525',
 'col526',
 'col527',
 'col528',
 'col529',
 'col530',
 'col531',
 'col532',
 'col533',
 'col534',
 'col535',
 'col536',
 'col537',
 'col538',
 'col539',
 'col540',
 'col541',
 'col542',
 'col543',
 'col544',
 'col545',
 'col546',
 'col547',
 'col548',
 'col549',
 'col550',
 'col551',
 'col552',
 'col553',
 'col554',
 'col555',
 'col556',
 'col557',
 'col558',
 'col559',
 'col560',
 'col561',
 'col562',
 'col563',
 'col564',
 'col565',
 'col566',
 'col567',
 'col568',
 'col569',
 'col570',
 'col571',
 'col572',
 'col573',
 'col574',
 'col575',
 'col576',
 'col577',
 'col578',
 'col579',
 'col580',
 'col581',
 'col582',
 'col583',
 'col584',
 'col585',
 'col586',
 'col587',
 'col588',
 'col589',
 'col590',
 'col591',
 'col592',
 'col593',
 'col594',
 'col595',
 'col596',
 'col597',
 'col598',
 'col599',
 'col600',
 'col601',
 'col602',
 'col603',
 'col604',
 'col605',
 'col606',
 'col607',
 'col608',
 'col609',
 'col610',
 'col611',
 'col612',
 'col613',
 'col614',
 'col615',
 'col616',
 'col793',
 'col794',
 'col795',
 'col796',
 'col797',
 'col798',
 'col799',
 'col800',
 'col819',
 'col820',
 'col823',
 'col824',
 'col1029',
 'col1030',
 'col1031',
 'col1032',
 'col1033',
 'col1034',
 'col1035',
 'col1036',
 'col1037',
 'col1038',
 'col1039',
 'col1040',
 'col1041',
 'col1042',
 'col1043',
 'col1044',
 'col1045',
 'col1046',
 'col1047',
 'col1048',
 'col1049',
 'col1050',
 'col1051',
 'col1052',
 'col1053',
 'col1054',
 'col1055',
 'col1056',
 'col1057',
 'col1058',
 'col1059',
 'col1060',
 'col1061',
 'col1062',
 'col1063',
 'col1064',
 'col1065',
 'col1066',
 'col1067',
 'col1068',
 'col1070',
 'col1071',
 'col1072',
 'col1073',
 'col1074',
 'col1075',
 'col1076',
 'col1170',
 'col1171',
 'col1172',
 'col1174',
 'col1175',
 'col1176',
 'col1177',
 'col1178',
 'col1179',
 'col1180',
 'col1273',
 'col1274',
 'col1275',
 'col1276',
 'col1277',
 'col1278',
 'col1279',
 'col1280',
 'col1445',
 'col1446',
 'col1447',
 'col1448',
 'col1449',
 'col1450',
 'col1451',
 'col1452',
 'col1454',
 'col1647',
 'col1648',
 'col1649',
 'col1650',
 'col1651',
 'col1652',
 'col1653',
 'col1654',
 'col2191',
 'col2192',
 'col2193',
 'col2194',
 'col2195',
 'col2196',
 'col2197',
 'col2198']

# Создание первых фич

## Создание шумовых фич

In [29]:
data['noise_5'] = np.random.randint(low=0, high=4, size=len(data))
data['noise_05'] = np.random.normal(0.5, 0.2)

## Создание лишнего таргета

In [30]:
sorted(Counter(data[['client_id','target']].groupby('client_id').count()['target']).items())

[(1, 1187),
 (2, 1077),
 (3, 935),
 (4, 667),
 (5, 461),
 (6, 267),
 (7, 115),
 (8, 66),
 (9, 25),
 (10, 11),
 (11, 5),
 (12, 1)]

In [31]:
sorted(Counter(data[['client_id','target']].groupby('client_id').sum()['target']).items())

[(0, 4634), (1, 41), (2, 31), (3, 111)]

In [36]:
dict_2 = data[['client_id','target']].groupby('client_id').max().reset_index().set_index('client_id').to_dict()['target']
dict_2

{1: 0,
 2: 0,
 5: 0,
 6: 0,
 7: 0,
 8: 0,
 10: 0,
 14: 0,
 15: 0,
 16: 0,
 17: 0,
 18: 0,
 19: 0,
 21: 0,
 22: 0,
 23: 0,
 24: 0,
 25: 0,
 26: 0,
 27: 0,
 28: 0,
 29: 0,
 30: 0,
 31: 0,
 32: 0,
 33: 0,
 34: 0,
 35: 0,
 36: 0,
 37: 0,
 38: 0,
 39: 0,
 40: 0,
 42: 0,
 43: 0,
 44: 0,
 45: 0,
 46: 0,
 47: 0,
 48: 0,
 49: 0,
 50: 0,
 51: 1,
 52: 0,
 53: 0,
 54: 0,
 55: 0,
 56: 0,
 57: 0,
 58: 0,
 59: 0,
 60: 0,
 63: 0,
 64: 0,
 65: 0,
 66: 0,
 67: 0,
 68: 0,
 69: 0,
 70: 0,
 71: 0,
 72: 0,
 74: 0,
 75: 0,
 76: 0,
 77: 0,
 78: 0,
 79: 0,
 81: 0,
 82: 0,
 83: 0,
 84: 0,
 87: 0,
 89: 0,
 90: 0,
 91: 0,
 92: 0,
 93: 0,
 96: 0,
 99: 0,
 101: 0,
 102: 0,
 103: 0,
 105: 0,
 106: 0,
 107: 0,
 109: 0,
 110: 0,
 111: 0,
 112: 0,
 113: 0,
 114: 0,
 115: 0,
 116: 0,
 118: 0,
 119: 0,
 121: 0,
 122: 0,
 123: 0,
 126: 0,
 128: 0,
 130: 0,
 131: 0,
 133: 0,
 134: 0,
 135: 0,
 136: 0,
 137: 0,
 138: 0,
 139: 0,
 140: 0,
 141: 0,
 143: 0,
 147: 0,
 149: 0,
 151: 0,
 152: 0,
 153: 0,
 154: 0,
 155: 0,
 156: 0,
 157: 0,
 159: 0,
 160: 0,
 161: 0,
 162: 0,
 163: 0,
 164: 0,
 165: 0,
 166: 0,
 167: 0,
 169: 0,
 170: 0,
 171: 0,
 172: 0,
 173: 0,
 174: 0,
 176: 0,
 177: 0,
 178: 0,
 179: 0,
 180: 0,
 181: 0,
 182: 0,
 183: 0,
 184: 0,
 185: 0,
 186: 0,
 187: 0,
 188: 0,
 189: 0,
 190: 0,
 191: 0,
 192: 0,
 193: 0,
 194: 0,
 197: 0,
 198: 0,
 199: 0,
 200: 0,
 202: 0,
 203: 0,
 204: 0,
 205: 0,
 207: 0,
 208: 0,
 209: 0,
 210: 1,
 211: 0,
 212: 0,
 215: 0,
 216: 0,
 217: 0,
 218: 0,
 219: 0,
 220: 0,
 221: 0,
 222: 0,
 223: 0,
 224: 0,
 225: 0,
 226: 0,
 227: 0,
 228: 0,
 230: 0,
 231: 0,
 232: 0,
 233: 0,
 234: 0,
 235: 0,
 237: 0,
 238: 0,
 239: 0,
 241: 0,
 242: 0,
 243: 0,
 244: 0,
 245: 0,
 246: 0,
 248: 0,
 249: 0,
 251: 0,
 254: 0,
 255: 0,
 256: 0,
 257: 0,
 258: 0,
 262: 0,
 263: 0,
 264: 1,
 265: 0,
 266: 0,
 267: 0,
 268: 0,
 270: 0,
 271: 0,
 272: 0,
 274: 0,
 275: 0,
 276: 0,
 280: 0,
 281: 0,
 282: 0,
 283: 0,
 284: 0,
 285: 0,
 286: 0,
 287: 0,
 288: 0,
 289: 0,
 290: 0,
 291: 0,
 292: 0,
 293: 0,
 294: 0,
 295: 0,
 297: 0,
 298: 0,
 299: 0,
 300: 1,
 302: 1,
 303: 1,
 305: 0,
 306: 0,
 307: 0,
 308: 0,
 309: 0,
 310: 0,
 311: 0,
 312: 0,
 313: 0,
 314: 0,
 318: 0,
 319: 0,
 321: 0,
 322: 0,
 323: 0,
 324: 0,
 327: 0,
 328: 0,
 329: 0,
 331: 0,
 332: 0,
 333: 0,
 334: 0,
 335: 0,
 336: 0,
 337: 0,
 339: 0,
 340: 0,
 341: 0,
 342: 0,
 343: 0,
 344: 0,
 345: 0,
 346: 0,
 348: 0,
 351: 0,
 352: 0,
 353: 0,
 354: 1,
 356: 0,
 358: 0,
 359: 0,
 360: 0,
 361: 0,
 362: 0,
 363: 0,
 364: 0,
 365: 0,
 366: 0,
 367: 0,
 368: 0,
 369: 0,
 370: 0,
 371: 0,
 372: 0,
 373: 0,
 374: 0,
 375: 0,
 376: 0,
 377: 0,
 378: 0,
 379: 0,
 380: 0,
 383: 0,
 384: 0,
 385: 0,
 386: 0,
 387: 0,
 388: 0,
 390: 0,
 393: 0,
 394: 0,
 395: 0,
 396: 0,
 397: 0,
 399: 0,
 400: 0,
 401: 0,
 402: 0,
 403: 0,
 404: 0,
 405: 0,
 406: 0,
 407: 0,
 408: 0,
 409: 0,
 410: 0,
 411: 0,
 412: 0,
 414: 0,
 415: 1,
 416: 0,
 417: 0,
 418: 0,
 419: 0,
 420: 1,
 421: 0,
 422: 0,
 423: 0,
 426: 0,
 427: 0,
 428: 0,
 429: 0,
 430: 0,
 431: 0,
 433: 0,
 434: 0,
 436: 0,
 437: 0,
 438: 0,
 439: 0,
 442: 0,
 443: 0,
 444: 0,
 445: 0,
 446: 0,
 448: 0,
 449: 1,
 450: 0,
 452: 0,
 453: 0,
 454: 0,
 456: 0,
 457: 0,
 458: 0,
 459: 0,
 460: 0,
 461: 0,
 463: 0,
 464: 0,
 466: 0,
 467: 0,
 468: 0,
 469: 0,
 470: 0,
 471: 0,
 472: 0,
 473: 1,
 474: 1,
 475: 1,
 476: 0,
 477: 1,
 478: 0,
 479: 0,
 480: 0,
 481: 0,
 482: 0,
 483: 0,
 485: 0,
 486: 0,
 487: 0,
 489: 0,
 490: 0,
 491: 0,
 494: 0,
 496: 0,
 497: 0,
 498: 0,
 501: 0,
 502: 0,
 503: 0,
 505: 0,
 506: 0,
 508: 0,
 509: 0,
 510: 0,
 511: 0,
 512: 0,
 513: 0,
 514: 0,
 515: 0,
 516: 0,
 517: 0,
 518: 0,
 519: 0,
 521: 0,
 522: 0,
 523: 0,
 524: 0,
 525: 0,
 526: 0,
 527: 0,
 529: 0,
 530: 1,
 532: 0,
 533: 0,
 534: 0,
 535: 0,
 536: 0,
 537: 0,
 538: 0,
 540: 0,
 541: 0,
 542: 0,
 543: 0,
 544: 0,
 545: 0,
 546: 0,
 548: 0,
 550: 0,
 551: 0,
 552: 0,
 553: 0,
 554: 0,
 555: 0,
 557: 0,
 558: 0,
 559: 0,
 560: 0,
 561: 0,
 562: 0,
 563: 0,
 565: 0,
 566: 0,
 567: 0,
 568: 1,
 570: 0,
 571: 0,
 572: 0,
 573: 0,
 576: 0,
 578: 0,
 579: 0,
 580: 0,
 582: 0,
 583: 0,
 584: 1,
 585: 0,
 586: 0,
 587: 0,
 588: 0,
 590: 0,
 591: 0,
 592: 0,
 593: 0,
 594: 0,
 595: 0,
 596: 0,
 597: 0,
 598: 0,
 599: 1,
 600: 0,
 601: 0,
 602: 0,
 604: 0,
 605: 0,
 607: 1,
 611: 0,
 612: 0,
 613: 0,
 614: 0,
 615: 0,
 616: 0,
 618: 0,
 619: 0,
 620: 0,
 621: 0,
 622: 0,
 623: 0,
 625: 0,
 626: 0,
 627: 0,
 628: 0,
 629: 0,
 630: 0,
 632: 0,
 633: 0,
 635: 0,
 636: 0,
 637: 0,
 638: 0,
 639: 0,
 640: 0,
 641: 0,
 642: 0,
 643: 0,
 644: 0,
 645: 0,
 646: 0,
 648: 0,
 650: 0,
 651: 0,
 652: 0,
 653: 0,
 656: 0,
 657: 0,
 659: 0,
 660: 0,
 661: 0,
 662: 0,
 663: 0,
 665: 0,
 666: 0,
 667: 0,
 668: 0,
 670: 0,
 673: 0,
 674: 0,
 675: 0,
 676: 0,
 677: 0,
 678: 0,
 679: 0,
 681: 0,
 682: 0,
 683: 0,
 685: 0,
 686: 0,
 687: 0,
 689: 0,
 690: 0,
 691: 0,
 692: 0,
 693: 0,
 694: 0,
 695: 0,
 696: 0,
 697: 0,
 698: 0,
 700: 0,
 702: 0,
 703: 0,
 704: 0,
 705: 0,
 706: 0,
 707: 0,
 708: 0,
 709: 0,
 710: 0,
 711: 0,
 712: 0,
 713: 0,
 714: 0,
 715: 0,
 716: 0,
 717: 0,
 718: 0,
 720: 0,
 721: 0,
 722: 0,
 723: 0,
 724: 0,
 727: 0,
 728: 0,
 729: 0,
 730: 0,
 731: 0,
 732: 0,
 733: 0,
 734: 0,
 735: 0,
 737: 0,
 738: 0,
 739: 0,
 740: 0,
 741: 0,
 742: 0,
 744: 0,
 745: 0,
 746: 0,
 747: 0,
 749: 0,
 751: 0,
 752: 0,
 753: 0,
 754: 0,
 755: 0,
 756: 0,
 757: 0,
 758: 0,
 759: 0,
 760: 1,
 761: 0,
 762: 0,
 763: 0,
 764: 0,
 766: 0,
 768: 0,
 769: 0,
 770: 0,
 772: 0,
 773: 0,
 774: 0,
 775: 0,
 776: 0,
 777: 0,
 779: 0,
 780: 0,
 781: 0,
 784: 0,
 785: 0,
 786: 0,
 787: 0,
 789: 0,
 790: 0,
 791: 0,
 792: 0,
 793: 0,
 795: 0,
 796: 1,
 797: 0,
 799: 0,
 801: 0,
 802: 0,
 803: 0,
 804: 0,
 805: 0,
 806: 0,
 807: 0,
 808: 0,
 809: 0,
 810: 0,
 813: 0,
 815: 0,
 816: 0,
 818: 0,
 820: 0,
 821: 0,
 822: 0,
 823: 0,
 824: 0,
 825: 0,
 826: 0,
 828: 0,
 830: 0,
 831: 0,
 834: 0,
 835: 0,
 836: 0,
 837: 0,
 838: 0,
 839: 0,
 840: 0,
 841: 0,
 842: 0,
 843: 0,
 844: 0,
 845: 0,
 846: 0,
 847: 0,
 848: 0,
 849: 0,
 850: 0,
 851: 0,
 852: 0,
 853: 0,
 854: 0,
 855: 0,
 856: 0,
 857: 0,
 858: 0,
 861: 0,
 862: 0,
 864: 0,
 866: 0,
 867: 0,
 868: 0,
 869: 0,
 870: 0,
 871: 0,
 872: 0,
 873: 0,
 875: 0,
 876: 0,
 878: 0,
 879: 0,
 881: 0,
 882: 0,
 883: 0,
 884: 0,
 885: 0,
 886: 0,
 887: 0,
 888: 0,
 889: 0,
 890: 0,
 891: 0,
 892: 0,
 893: 0,
 894: 0,
 895: 0,
 897: 0,
 898: 0,
 899: 0,
 900: 0,
 903: 0,
 904: 0,
 905: 0,
 906: 0,
 907: 0,
 909: 0,
 910: 0,
 912: 0,
 913: 0,
 915: 0,
 916: 0,
 917: 0,
 918: 0,
 920: 0,
 922: 0,
 923: 0,
 925: 0,
 926: 0,
 927: 0,
 928: 0,
 929: 0,
 932: 0,
 933: 0,
 935: 0,
 936: 0,
 938: 0,
 939: 0,
 940: 0,
 941: 0,
 942: 0,
 943: 0,
 944: 0,
 945: 0,
 946: 0,
 947: 1,
 948: 0,
 949: 0,
 951: 0,
 952: 0,
 953: 0,
 955: 0,
 956: 0,
 957: 0,
 958: 1,
 960: 0,
 961: 0,
 963: 0,
 964: 0,
 966: 0,
 967: 1,
 968: 0,
 969: 0,
 970: 0,
 971: 0,
 972: 0,
 973: 0,
 974: 1,
 975: 0,
 976: 0,
 977: 0,
 979: 0,
 980: 0,
 982: 0,
 983: 0,
 984: 0,
 985: 0,
 986: 0,
 987: 0,
 988: 0,
 990: 0,
 991: 0,
 993: 0,
 994: 0,
 996: 0,
 997: 0,
 998: 0,
 999: 0,
 1000: 0,
 1001: 0,
 1003: 0,
 1005: 0,
 1006: 0,
 1007: 0,
 1008: 0,
 1009: 0,
 1010: 0,
 1011: 0,
 1012: 0,
 1013: 0,
 1015: 0,
 1016: 0,
 1018: 0,
 1019: 0,
 1020: 0,
 1021: 0,
 1022: 0,
 1023: 0,
 1024: 0,
 1025: 0,
 1026: 0,
 1027: 0,
 1028: 0,
 1029: 0,
 1030: 0,
 1031: 0,
 1032: 1,
 1033: 0,
 1034: 0,
 1035: 1,
 1036: 0,
 1037: 0,
 1038: 0,
 1039: 0,
 1040: 0,
 1041: 0,
 1042: 0,
 1043: 0,
 1045: 0,
 1046: 0,
 1048: 0,
 1049: 1,
 1050: 0,
 1051: 0,
 1052: 0,
 1053: 0,
 1054: 0,
 1055: 0,
 1056: 0,
 1059: 0,
 1060: 0,
 1061: 0,
 1062: 0,
 1064: 0,
 1065: 0,
 1066: 0,
 1067: 0,
 1068: 0,
 1069: 0,
 1070: 0,
 1072: 0,
 1073: 0,
 1074: 0,
 1075: 0,
 1076: 0,
 1077: 0,
 1079: 0,
 1080: 0,
 1081: 0,
 1082: 0,
 1083: 0,
 1084: 0,
 1085: 0,
 1086: 0,
 1087: 0,
 1088: 0,
 1089: 0,
 1090: 0,
 1091: 0,
 1094: 0,
 1095: 0,
 1096: 0,
 1097: 0,
 1098: 0,
 1099: 1,
 1100: 0,
 1102: 0,
 1103: 0,
 1104: 0,
 1105: 0,
 1106: 0,
 1107: 0,
 1109: 0,
 1110: 0,
 1111: 0,
 1112: 0,
 1113: 0,
 1115: 0,
 1117: 1,
 1118: 0,
 1120: 0,
 1121: 0,
 1123: 0,
 1124: 0,
 1125: 0,
 1126: 0,
 1127: 0,
 1128: 0,
 1129: 0,
 1132: 0,
 1133: 0,
 1134: 0,
 1135: 0,
 1136: 1,
 1138: 0,
 1139: 0,
 1140: 0,
 1141: 0,
 1145: 0,
 1148: 0,
 1149: 0,
 1150: 1,
 1151: 0,
 1153: 0,
 1154: 0,
 1155: 0,
 1157: 0,
 1158: 0,
 1159: 0,
 1160: 0,
 1162: 0,
 1163: 0,
 1164: 1,
 1165: 0,
 1166: 0,
 1167: 0,
 1169: 0,
 1170: 0,
 1172: 0,
 1173: 0,
 1174: 0,
 1175: 0,
 1177: 0,
 1178: 0,
 1179: 0,
 1180: 0,
 1183: 0,
 1184: 0,
 1185: 0,
 1186: 0,
 1187: 0,
 1188: 0,
 1190: 0,
 1191: 0,
 1193: 0,
 1194: 0,
 1196: 0,
 1199: 0,
 1201: 0,
 1202: 0,
 1204: 0,
 1205: 0,
 1207: 0,
 1208: 0,
 1209: 0,
 1210: 0,
 1211: 0,
 1212: 0,
 1213: 0,
 1214: 0,
 1215: 0,
 1216: 0,
 1217: 0,
 1218: 0,
 1219: 0,
 1220: 0,
 1222: 0,
 1223: 0,
 1224: 0,
 1225: 0,
 1226: 0,
 1227: 0,
 1228: 0,
 1229: 0,
 1230: 0,
 1232: 0,
 1233: 0,
 1234: 0,
 1235: 0,
 1236: 0,
 1237: 0,
 1238: 0,
 1239: 0,
 1240: 0,
 ...}

In [38]:
np.cos(3.14)

-0.9999987317275395

In [39]:
'2022-11-01'[5:-3]

'11'

In [40]:
data['target_2'] = list(map(lambda x: dict_2[x], data['client_id']))
data['mnth'] = data['report_date'].apply(lambda x: np.cos(int(x[5:-3])/2))
data

,report_date,client_id,target,col1,col2,col3,col4,col5,col6,col7,...,col2658,col2659,col2660,col2661,col2662,col2663,noise_5,noise_05,target_2,mnth
0,2022-11-01,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.256261,0,0.882691,0,0.708670
1,2022-11-01,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,7616803.0,7616803.0,7616803.0,0.256261,0,0.882691,0,0.708670
2,2022-05-01,6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.256261,2,0.882691,0,-0.801144
3,2022-09-01,7,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.258682,3,0.882691,0,-0.210796
4,2022-08-01,8,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.254164,3,0.882691,0,-0.653644
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14451,2022-07-01,1241,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.276902,2,0.882691,0,-0.936457
14452,2022-09-01,1969,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.260516,2,0.882691,1,-0.210796
14453,2022-02-01,7116,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.260005,0,0.882691,1,0.540302
14454,2021-08-01,7117,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.256261,1,0.882691,0,-0.653644
14455,2022-03-01,849,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.293904,0,0.882691,0,0.070737

# Первый слой 🧅

In [ ]:
obj_cols.remove('col1454')
obj_cols.remove('report_date')

In [97]:
import pandas as pd
from sklearn.model_selection import StratifiedGroupKFold

our_models = []

need_columns = ['target','client_id','col1454','report_date','target_2'] # столбцы нужные для удаления 

# Определите целевую переменную и группировочную переменную (client_id)
X = data.drop(columns=need_columns).fillna(-404)
y = data['target']
groups = data['client_id']

# Создайте объект StratifiedGroupKFold и задайте количество фолдов
n_splits = 5  # Задайте нужное количество фолдов
sgkf = StratifiedGroupKFold(n_splits=n_splits)

# Проходите по каждому фолду
for fold, (train_idx, val_idx) in enumerate(sgkf.split(X, y, groups)):
    # Далее вы можете использовать train_idx и val_idx для разделения данных на обучающий и валидационный фолд
    train_data = data.iloc[train_idx]
    val_data = data.iloc[val_idx]
    
    
    
    
    
    X_train = train_data.drop(need_columns, axis=1).fillna(-404)
    y_train = train_data['target']
    
    X_test = val_data.drop(need_columns, axis=1).fillna(-404)
    y_test = val_data['target']
    
    train_pool = Pool(data=X_train, label=y_train,  cat_features = obj_cols)
    test_pool = Pool(data=X_test, label=y_test,  cat_features = obj_cols)

    # Создайте объект модели CatBoostClassifier
    model = CatBoostClassifier(iterations= 100,
          depth= 7,
          loss_function='Logloss', auto_class_weights="Balanced",
        boosting_type='Ordered', l2_leaf_reg= 3,
          eval_metric='AUC',
          learning_rate= 0.05,
            custom_metric = ['MCC','Accuracy','Precision','Recall','F1','NormalizedGini']
          ) 

    # Обучите модель на обучающем Pool
    model.fit(train_pool, eval_set=test_pool,verbose= False,
        plot=True,
         use_best_model= True
            )
    

    our_models += [model]

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [98]:

importance_df.Importances.mean()

0.03752345215759853

In [99]:
importance_df = our_models[0].get_feature_importance(prettified=True)
stop_index = importance_df[(importance_df['Importances'] <= 0.00005)].index[0]
set_of_good_features = set(importance_df['Feature Id'][:stop_index].to_list())
for i in range(5): 
    importance_df = our_models[i].get_feature_importance(prettified=True)
    stop_index = importance_df[(importance_df['Importances'] <= 0.00005)].index[0]
    new_set = set(importance_df['Feature Id'][:stop_index].to_list())
    set_of_good_features = set_of_good_features & new_set

In [100]:
list(set_of_good_features)

['col2366',
 'col2388',
 'col2340',
 'col2382',
 'col2360',
 'col2220',
 'col2663',
 'col2294']

# Второй слой 🧅🧅

In [4]:
set_of_good_features = set(['col2366',
 'col2388',
 'col2340',
 'col2382',
 'col2360',
 'col2220',
 'col2663',
 'col2294'])

In [5]:
set_of_good_features

{'col2220',
 'col2294',
 'col2340',
 'col2360',
 'col2366',
 'col2382',
 'col2388',
 'col2663'}

In [6]:
import pandas as pd
from sklearn.model_selection import StratifiedGroupKFold

our_models_2 = []

need_columns = ['target','client_id','col1454','report_date'] # столбцы нужные для удаления 

# Определите целевую переменную и группировочную переменную (client_id)
X = data.drop(columns=need_columns).fillna(-404)
y = data['target']
groups = data['client_id']

# Создайте объект StratifiedGroupKFold и задайте количество фолдов
n_splits = 5  # Задайте нужное количество фолдов
sgkf = StratifiedGroupKFold(n_splits=n_splits)

# Проходите по каждому фолду
for fold, (train_idx, val_idx) in enumerate(sgkf.split(X, y, groups)):
    # Далее вы можете использовать train_idx и val_idx для разделения данных на обучающий и валидационный фолд
    train_data = data.iloc[train_idx]
    val_data = data.iloc[val_idx]
    
    
    
    
    
    X_train = train_data[list(set_of_good_features)]
    y_train = train_data['target']
    
    X_test = val_data[list(set_of_good_features)]
    y_test = val_data['target']
    
    train_pool = Pool(data=X_train, label=y_train)
    test_pool = Pool(data=X_test, label=y_test)

    # Создайте объект модели CatBoostClassifier
    model = CatBoostClassifier(iterations= 100,
          depth= 6,
          loss_function='Logloss', auto_class_weights="Balanced",
        boosting_type='Ordered', l2_leaf_reg= 3,
          eval_metric='AUC',
          learning_rate= 0.01,
            custom_metric = ['MCC','Accuracy','Precision','Recall','F1','NormalizedGini']
          ) 

    # Обучите модель на обучающем Pool
    model.fit(train_pool, eval_set=test_pool,verbose= False,
        plot=True,
         use_best_model= True
            )
    

    our_models_2 += [model]

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

# Feature инжиниринг

In [115]:
good_features = list(set_of_good_features)

def pw_prod(df):
    for col1 in list(set_of_good_features):
        for col2 in list(set_of_good_features):
            
            df[f'{col1}+{col2}'] = list(np.array(df[col1]) + np.array(df[col2]))
            df[f'{col1}-{col2}'] = list(np.array(df[col1]) - np.array(df[col2]))
            df[f'{col1}*{col2}'] = list(np.array(df[col1]) * np.array(df[col2]))
            df[f'{col1}/{col2}'] = list(np.array(df[col1]) / np.array(df[col2]))
            
for col1 in list(set_of_good_features):
    for col2 in list(set_of_good_features):
        good_features += [f'{col1}+{col2}']
        good_features += [f'{col1}-{col2}']
        good_features += [f'{col1}*{col2}']
        good_features += [f'{col1}/{col2}']
            
            
            
good_features = list(set(good_features))
pw_prod(data)

C:\Users\MgDuck\AppData\Local\Temp\ipykernel_28368\2739763497.py:10: RuntimeWarning: divide by zero encountered in true_divide
  df[f'{col1}/{col2}'] = list(np.array(df[col1]) / np.array(df[col2]))
C:\Users\MgDuck\AppData\Local\Temp\ipykernel_28368\2739763497.py:10: RuntimeWarning: invalid value encountered in true_divide
  df[f'{col1}/{col2}'] = list(np.array(df[col1]) / np.array(df[col2]))

In [116]:
data

,report_date,client_id,target,col1,col2,col3,col4,col5,col6,col7,...,col2294*col2220,col2294/col2220,col2294+col2663,col2294-col2663,col2294*col2663,col2294/col2663,col2294+col2294,col2294-col2294,col2294*col2294,col2294/col2294
0,2022-11-01,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.984070e+07,2.253590e-06,15.256261,14.743739,3.843921,58.533986,30.0,0.0,225.00,1.0
1,2022-11-01,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.867796e+07,4.271573e-07,3.756261,3.243739,0.896915,13.657930,7.0,0.0,12.25,1.0
2,2022-05-01,6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.064368e+08,2.405184e-06,16.256261,15.743739,4.100182,62.436251,32.0,0.0,256.00,1.0
3,2022-09-01,7,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.000000e+04,8.000000e-04,8.258682,7.741318,2.069454,30.926030,16.0,0.0,64.00,1.0
4,2022-08-01,8,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.232866e+08,2.579644e-06,24.254164,23.745836,6.099943,94.427110,48.0,0.0,576.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14451,2022-07-01,1241,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.262918e+07,7.661853e-07,5.276902,4.723098,1.384510,18.056928,10.0,0.0,25.00,1.0
14452,2022-09-01,1969,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.590430e+08,1.115645e-06,17.260516,16.739484,4.428779,65.255005,34.0,0.0,289.00,1.0
14453,2022-02-01,7116,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.072510e+08,9.323925e-07,10.260005,9.739995,2.600054,38.460737,20.0,0.0,100.00,1.0
14454,2021-08-01,7117,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.645432e+07,9.875374e-07,6.256261,5.743739,1.537568,23.413594,12.0,0.0,36.00,1.0
14455,2022-03-01,849,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.782022e+07,7.287616e-07,8.293904,7.706096,2.351231,27.219784,16.0,0.0,64.00,1.0

# Третий слой 🧅

In [121]:
import pandas as pd
from sklearn.model_selection import StratifiedGroupKFold

our_models_3 = []

need_columns = ['target','client_id','col1454','report_date','target_2'] # столбцы нужные для удаления 

# Определите целевую переменную и группировочную переменную (client_id)
X = data.drop(columns=need_columns).fillna(-404)
y = data['target']
groups = data['client_id']

# Создайте объект StratifiedGroupKFold и задайте количество фолдов
n_splits = 5  # Задайте нужное количество фолдов
sgkf = StratifiedGroupKFold(n_splits=n_splits)

# Проходите по каждому фолду
for fold, (train_idx, val_idx) in enumerate(sgkf.split(X, y, groups)):
    # Далее вы можете использовать train_idx и val_idx для разделения данных на обучающий и валидационный фолд
    train_data = data.iloc[train_idx]
    val_data = data.iloc[val_idx]
    
    
    
    
    
    X_train = train_data[good_features]
    y_train = train_data['target']
    
    X_test = val_data[good_features]
    y_test = val_data['target']
    
    train_pool = Pool(data=X_train, label=y_train)
    test_pool = Pool(data=X_test, label=y_test)

    # Создайте объект модели CatBoostClassifier
    model = CatBoostClassifier(iterations= 200,
          depth= 7,
          loss_function='Logloss', auto_class_weights="Balanced",
        boosting_type='Ordered', l2_leaf_reg= 3,
          eval_metric='AUC',
          learning_rate= 0.05,
            custom_metric = ['MCC','Accuracy','Precision','Recall','F1','NormalizedGini']
          ) 

    # Обучите модель на обучающем Pool
    model.fit(train_pool, eval_set=test_pool,verbose= False,
        plot=True,
         use_best_model= True
            )
    

    our_models_3 += [model]

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

# Эвристика 42

In [124]:
sum_dict = data[['client_id','target']].groupby('client_id').sum().reset_index().set_index('client_id').to_dict()['target']
count_dict = data[['client_id','target']].groupby('client_id').count().reset_index().set_index('client_id').to_dict()['target']

In [169]:
temp_dict = {}
target_3 = []
data = data.sort_values('report_date')
for clid in data.client_id:
    if clid not in temp_dict.keys():
        temp_dict[clid] = 1
    else:
        temp_dict[clid] += 1
    
    if sum_dict[clid] == 0:
        target_3 += [0]
    elif temp_dict[clid] == (count_dict[clid] - sum_dict[clid]):
        target_3 += [1]
    elif temp_dict[clid] < (count_dict[clid] - sum_dict[clid]):
        target_3 += [0]
    else:
        target_3 += [2]

In [172]:
Counter(target_3)

Counter({0: 13947, 2: 436, 1: 73})

In [173]:
data['target_3'] = target_3
data

,report_date,client_id,target,col1,col2,col3,col4,col5,col6,col7,...,col2294/col2220,col2294+col2663,col2294-col2663,col2294*col2663,col2294/col2663,col2294+col2294,col2294-col2294,col2294*col2294,col2294/col2294,target_3
9374,2021-02-01,491,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.191597e-06,10.256261,9.743739,2.562614,39.022657,20.0,0.0,100.0,1.0,0
2289,2021-02-01,359,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.344574e-06,8.256261,7.743739,2.050091,31.218126,16.0,0.0,64.0,1.0,0
8035,2021-02-01,637,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.964839e-06,32.256261,31.743739,8.200364,124.872502,64.0,0.0,1024.0,1.0,0
2286,2021-02-01,2895,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.291846e-06,10.256261,9.743739,2.562614,39.022657,20.0,0.0,100.0,1.0,0
2758,2021-02-01,3302,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3832,2023-02-01,4174,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.869632e-06,14.261248,13.738752,3.657468,53.588980,28.0,0.0,196.0,1.0,0
2901,2023-02-01,3429,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.296181e-06,6.256261,5.743739,1.537568,23.413594,12.0,0.0,36.0,1.0,0
13351,2023-02-01,4000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.523230e-06,16.257217,15.742783,4.115479,62.204184,32.0,0.0,256.0,1.0,0
7283,2023-02-01,5716,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.287614e-07,1.256437,0.743563,0.256437,3.899589,2.0,0.0,1.0,1.0,0
12107,2023-02-01,4916,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.204724e-06,8.256261,7.743739,2.050091,31.218126,16.0,0.0,64.0,1.0,0

In [177]:
import pandas as pd
from sklearn.model_selection import StratifiedGroupKFold


our_models_42 = []

need_columns = ['target','client_id','col1454','report_date','target_2', 'target_3'] # столбцы нужные для удаления 

# Определите целевую переменную и группировочную переменную (client_id)
X = data.drop(columns=need_columns).fillna(-404)
y = data['target_3']
groups = data['client_id']

# Создайте объект StratifiedGroupKFold и задайте количество фолдов
n_splits = 5  # Задайте нужное количество фолдов
sgkf = StratifiedGroupKFold(n_splits=n_splits)

# Проходите по каждому фолду
for fold, (train_idx, val_idx) in enumerate(sgkf.split(X, y, groups)):
    # Далее вы можете использовать train_idx и val_idx для разделения данных на обучающий и валидационный фолд
    train_data = data.iloc[train_idx]
    val_data = data.iloc[val_idx]
    
    
    
    
    
    X_train = train_data.drop(need_columns, axis=1).fillna(-404)
    y_train = train_data['target_3']
    
    X_test = val_data.drop(need_columns, axis=1).fillna(-404)
    y_test = val_data['target_3']
    
    train_pool = Pool(data=X_train, label=y_train,  cat_features = obj_cols)
    test_pool = Pool(data=X_test, label=y_test,  cat_features = obj_cols)
    
    

    
    
    # Создайте объект модели CatBoostClassifier
    model = CatBoostClassifier(iterations= 70,
          depth= 6,
          loss_function='MultiClass', auto_class_weights="Balanced",
        boosting_type='Ordered', l2_leaf_reg= 3,
          eval_metric='AUC',
          learning_rate= 0.07,
            custom_metric = ['MCC','Accuracy','Precision','Recall','F1','NormalizedGini']
          ) 

    # Обучите модель на обучающем Pool
    model.fit(train_pool, eval_set=test_pool,verbose= False,
        plot=True,
         use_best_model= True
            )
    

    our_models_42 += [model]

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [204]:
roc_auc_score(data['target'],list(map(lambda x:x[1] * 0.5 + x[2] ,our_models_42[0].predict(X,prediction_type='Probability'))))

0.8151065319530423

# Процесс предсказания

In [7]:
tst = pd.read_csv('test.csv', low_memory=False, sep=';')
tst

,report_date,client_id,col1,col2,col3,col4,col5,col6,col7,col8,...,col2655,col2656,col2657,col2658,col2659,col2660,col2661,col2662,col2663,id
0,2023-04-01,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4941670.0,4941670.0,NaN,NaN,NaN,4941670.0,4941670.0,4941670.0,0.256919,0
1,2023-05-01,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11789500.0,11789500.0,NaN,NaN,NaN,11789500.0,11789500.0,11789500.0,0.267221,1
2,2023-05-01,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7000000.0,7000000.0,NaN,NaN,NaN,7000000.0,7000000.0,7000000.0,0.257217,2
3,2023-03-01,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.256261,3
4,2023-03-01,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10391000.0,10391000.0,10391000.0,0.257348,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3637,2023-04-01,4366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3500000.0,3500000.0,3500000.0,0.256261,3637
3638,2023-04-01,8298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.256261,3638
3639,2023-03-01,835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.256919,3639
3640,2023-03-01,8300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.257217,3640
3641,2023-05-01,1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1400000.0,1400000.0,1400000.0,1400000.0,1400000.0,1400000.0,1400000.0,1400000.0,0.285755,3641

In [8]:
need_columns = ['id','client_id','col1454','report_date'] # столбцы нужные для удаления 

# Определите целевую переменную и группировочную переменную (client_id)
X = tst[['col2366',
 'col2388',
 'col2340',
 'col2382',
 'col2360',
 'col2220',
 'col2663',
 'col2294']].fillna(-404)
X

,col2366,col2388,col2340,col2382,col2360,col2220,col2663,col2294
0,1.0,30.09,5794341.03,30.09,1.0,6564363.20,0.256919,5.000000
1,2.0,63.51,13981124.40,63.51,2.0,13693099.02,0.267221,3.333333
2,2.0,49.92,11139747.84,49.92,2.0,12417006.76,0.257217,21.000000
3,2.0,37.60,10795110.40,-404.00,-404.0,10785110.30,0.256261,5.000000
4,1.0,37.05,9756932.25,-404.00,-404.0,9649462.80,0.257348,14.000000
...,...,...,...,...,...,...,...,...
3637,1.0,22.73,3906514.18,-404.00,-404.0,4318743.41,0.256261,2.000000
3638,2.0,56.90,16130694.80,-404.00,-404.0,15778680.67,0.256261,7.000000
3639,1.0,30.50,12149858.00,-404.00,-404.0,12619544.28,0.256919,14.000000
3640,2.0,54.63,11431108.98,54.63,2.0,14027694.75,0.257217,3.000000
3641,1.0,35.48,8442071.20,35.48,1.0,8239382.69,0.285755,2.800000

In [9]:
preds = our_models_2[0].predict(X,prediction_type='Probability')
mmm = np.array(list(map(lambda x: x[1],preds)))
for i in range(1,5):
    preds = our_models_2[i].predict(X,prediction_type='Probability')
    mmm += np.array(list(map(lambda x: x[1],preds)))
    print(np.array(list(map(lambda x: x[1],preds)))[:10])
target = mmm / 5

[0.36464556 0.68242254 0.5716573  0.38038045 0.44812824 0.38258733
 0.51364487 0.51251694 0.28884685 0.56486031]
[0.38058745 0.69456143 0.5998059  0.33900909 0.37256478 0.38372127
 0.54169313 0.46976654 0.28510047 0.55527541]
[0.36342305 0.69574329 0.60173005 0.33603051 0.40775978 0.34769809
 0.48456921 0.48398119 0.26747801 0.52127235]
[0.41471806 0.66224105 0.56277207 0.40391054 0.430351   0.41798006
 0.56776195 0.42119321 0.27394887 0.56345022]

In [10]:
tst['target'] = target
tst

,report_date,client_id,col1,col2,col3,col4,col5,col6,col7,col8,...,col2656,col2657,col2658,col2659,col2660,col2661,col2662,col2663,id,target
0,2023-04-01,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4941670.0,NaN,NaN,NaN,4941670.0,4941670.0,4941670.0,0.256919,0,0.390939
1,2023-05-01,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11789500.0,NaN,NaN,NaN,11789500.0,11789500.0,11789500.0,0.267221,1,0.666979
2,2023-05-01,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7000000.0,NaN,NaN,NaN,7000000.0,7000000.0,7000000.0,0.257217,2,0.579078
3,2023-03-01,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.256261,3,0.374736
4,2023-03-01,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,10391000.0,10391000.0,10391000.0,0.257348,4,0.424731
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3637,2023-04-01,4366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3500000.0,3500000.0,3500000.0,0.256261,3637,0.277026
3638,2023-04-01,8298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.256261,3638,0.400943
3639,2023-03-01,835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.256919,3639,0.409609
3640,2023-03-01,8300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.257217,3640,0.518917
3641,2023-05-01,1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1400000.0,1400000.0,1400000.0,1400000.0,1400000.0,1400000.0,1400000.0,0.285755,3641,0.531537

In [11]:
tst[['id','target']].to_csv('sub.csv',sep=';',index=False)

In [ ]:
len(our_models[0].get_feature_importance())

In [ ]:
len(X)

In [276]:
X = X[['col2366',
 'col2388',
 'col2340',
 'col2382',
 'col2360',
 'col2220',
 'col2663',
 'col2294']].fillna(-404)

In [278]:
np.array(list(map(lambda x: x[1],preds)))

array([0.47918002, 0.4850569 , 0.47918002, ..., 0.52819245, 0.47197118,
       0.49681692])